# Nome do fluxo de trabalho
name: Criar Release e Publicar Executável

# Gatilho: A automação é acionada quando uma tag que começa com 'v' é enviada.
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    # A tarefa DEVE ser executada em uma máquina virtual Windows para projetos WPF.
    runs-on: windows-latest
    
    # Adiciona permissão de escrita para o token da Action criar a Release.
    permissions:
      contents: write

    steps:
    # 1. Faz o checkout (download) do seu código para a máquina virtual
    - name: Checkout do código
      uses: actions/checkout@v4

    # 2. Instala a versão correta do .NET
    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 3. Restaura as dependências do seu projeto
    - name: Restaurar dependências
      run: dotnet restore supervisorioMMS.sln

    # 4. Compila e publica seu projeto para criar o .exe
    - name: Publicar a aplicação
      run: dotnet publish "supervisorioMMS/supervisorioMMS.csproj" -c Release --self-contained -r win-x64 -p:PublishSingleFile=true -o ./publish

    # 5. Cria a Release no GitHub e anexa o .exe
    - name: Criar Release e Anexar Executável
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish/supervisorioMMS.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
